name: flutter_app_skeleton
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.0.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  firebase_core: ^2.23.0
  firebase_crashlytics: ^3.4.5
  google_fonts: 6.1.0
  flutter_secure_storage: ^9.0.0
  dartz: ^0.10.1
  dio: ^5.3.4
  flutter_dotenv: ^5.1.0
  internet_connection_checker_plus: ^2.1.0
  intl: ^0.18.1
  brasil_fields: ^1.14.1
  collection: ^1.17.2
  shared_preferences: ^2.2.2
  diacritic: ^0.1.5
  jwt_decoder: ^2.0.1
  getwidget: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  bloc_test: ^9.1.5
  build_runner: ^2.4.6
  mockito: ^5.4.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - env/

